# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RTPopAnimation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RTPopAnimation

  pod 'RTAnimatedTransition', :path => '../'
  

  target 'RTPopAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RTPopAnimationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
